name: run-macos-14
on:
  workflow_dispatch:
    inputs:
      commands:
        type: string
        description: zsh commands to run
        required: true
      artifact-directory:
        type: string
        description: directory whose contents will be uploaded as artifacts
        required: false
defaults:
  run:
    shell: /bin/zsh -Negku {0}
jobs:
  run:
    runs-on: macos-14
    env:
      COMMANDS: ${{inputs.commands}}
    steps:
       - name: Run commands
         run: eval "${COMMANDS}"

       - name: Upload files as artifact
         if: inputs.artifact-directory != ''
         uses: actions/upload-artifact@v4
         with:
           name: output
           path: ${{inputs.artifact-directory}}*
